//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(void);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int64_t function_1003(void);
int64_t function_1060(int64_t a1);
void function_1063(int64_t * d);
int64_t function_1070(int64_t a1);
int32_t function_1073(int32_t c);
int64_t function_1080(void);
void function_1083(void);
int64_t function_1090(char * a1, int64_t a2);
int32_t function_1093(char * format, ...);
int64_t function_1143(void);
int64_t function_1183(void);
int64_t function_118c(int64_t a1, int64_t a2);
int64_t function_127b(void);
int64_t function_13b3(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1423(void);
int64_t function_142b(void);
int64_t register_tm_clones(void);
int64_t shit(int64_t * a1, int64_t a2, int32_t a3, int64_t a4);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1180; // 0x3da8
int64_t g2 = 0x1140; // 0x3db0
int64_t g3 = 0; // 0x4010
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int64_t _init(void) {
    // 0x1000
    int64_t result; // 0x1000
    return result;
}

// Address range: 0x1003 - 0x101b
int64_t function_1003(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g4;
    }
    // 0x1016
    return result;
}

// Address range: 0x1060 - 0x1061
int64_t function_1060(int64_t a1) {
    // 0x1060
    int64_t result; // 0x1060
    return result;
}

// Address range: 0x1063 - 0x106b
void function_1063(int64_t * d) {
    // 0x1063
    __cxa_finalize(d);
}

// Address range: 0x1070 - 0x1071
int64_t function_1070(int64_t a1) {
    // 0x1070
    int64_t result; // 0x1070
    return result;
}

// Address range: 0x1073 - 0x107b
int32_t function_1073(int32_t c) {
    // 0x1073
    return putchar(c);
}

// Address range: 0x1080 - 0x1081
int64_t function_1080(void) {
    // 0x1080
    int64_t result; // 0x1080
    return result;
}

// Address range: 0x1083 - 0x108b
void function_1083(void) {
    // 0x1083
    __stack_chk_fail();
}

// Address range: 0x1090 - 0x1091
int64_t function_1090(char * a1, int64_t a2) {
    // 0x1090
    int64_t result; // 0x1090
    return result;
}

// Address range: 0x1093 - 0x109b
int32_t function_1093(char * format, ...) {
    // 0x1093
    return printf(format);
}

// Address range: 0x10a0 - 0x10a1
int64_t _start(void) {
    // 0x10a0
    int64_t result; // 0x10a0
    return result;
}

// Address range: 0x10d0 - 0x10f9
int64_t deregister_tm_clones(void) {
    // 0x10d0
    return &g3;
}

// Address range: 0x1100 - 0x1139
int64_t register_tm_clones(void) {
    // 0x1100
    return 0;
}

// Address range: 0x1140 - 0x1141
int64_t __do_global_dtors_aux(void) {
    // 0x1140
    int64_t result; // 0x1140
    return result;
}

// Address range: 0x1143 - 0x1179
int64_t function_1143(void) {
    // 0x1143
    if (*(char *)&g3 != 0) {
        // 0x1178
        int64_t result; // 0x1143
        return result;
    }
    // 0x114d
    if (*(int64_t *)0x3ff8 != 0) {
        // 0x115b
        function_1060(*(int64_t *)0x4008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1167
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x1180 - 0x1181
int64_t frame_dummy(void) {
    // 0x1180
    int64_t result; // 0x1180
    return result;
}

// Address range: 0x1183 - 0x1189
int64_t function_1183(void) {
    // 0x1183
    return register_tm_clones();
}

// Address range: 0x1189 - 0x118a
int64_t shit(int64_t * a1, int64_t a2, int32_t a3, int64_t a4) {
    // 0x1189
    int64_t result; // 0x1189
    return result;
}

// Address range: 0x118c - 0x1278
int64_t function_118c(int64_t a1, int64_t a2) {
    int64_t v1 = 0x100000000 * a2 / 0x100000000; // 0x1195
    uint64_t result = v1 + 0xffffffff & 0xffffffff; // 0x1268
    if (result == 0) {
        // 0x1274
        return result;
    }
    int32_t v2 = 0; // 0x1261
    uint32_t v3 = -1 - v2 + (int32_t)v1; // 0x1255
    uint64_t v4 = (int64_t)v3; // 0x1255
    int32_t v5; // 0x118c
    int32_t * v6; // 0x11de
    uint32_t v7; // 0x11de
    int32_t v8; // 0x124b
    int64_t v9; // 0x125b
    int64_t v10; // 0x118c
    int32_t * v11; // 0x11c4
    uint32_t v12; // 0x11c4
    if (v3 != 0) {
        v10 = a1;
        v11 = (int32_t *)v10;
        v12 = *v11;
        v6 = (int32_t *)(v10 + 4);
        v7 = *v6;
        if (v12 < v7) {
            // 0x11e4
            *v11 = v7;
            *v6 = v12;
        }
        // 0x124b
        v8 = 1;
        v9 = v8;
        v5 = v8;
        while (v9 < v4) {
            // 0x11b0
            v10 = 4 * v9 + a1;
            v11 = (int32_t *)v10;
            v12 = *v11;
            v6 = (int32_t *)(v10 + 4);
            v7 = *v6;
            if (v12 < v7) {
                // 0x11e4
                *v11 = v7;
                *v6 = v12;
            }
            // 0x124b
            v8 = v5 + 1;
            v9 = v8;
            v5 = v8;
        }
    }
    // 0x1261
    v2++;
    while (result > (int64_t)v2) {
        // 0x124f
        v3 = -1 - v2 + (int32_t)v1;
        v4 = (int64_t)v3;
        if (v3 != 0) {
            v10 = a1;
            v11 = (int32_t *)v10;
            v12 = *v11;
            v6 = (int32_t *)(v10 + 4);
            v7 = *v6;
            if (v12 < v7) {
                // 0x11e4
                *v11 = v7;
                *v6 = v12;
            }
            // 0x124b
            v8 = 1;
            v9 = v8;
            v5 = v8;
            while (v9 < v4) {
                // 0x11b0
                v10 = 4 * v9 + a1;
                v11 = (int32_t *)v10;
                v12 = *v11;
                v6 = (int32_t *)(v10 + 4);
                v7 = *v6;
                if (v12 < v7) {
                    // 0x11e4
                    *v11 = v7;
                    *v6 = v12;
                }
                // 0x124b
                v8 = v5 + 1;
                v9 = v8;
                v5 = v8;
            }
        }
        // 0x1261
        v2++;
    }
    // 0x1274
    return result;
}

// Address range: 0x1278 - 0x1279
int main(int argc, char ** argv) {
    // 0x1278
    int64_t result; // 0x1278
    return result;
}

// Address range: 0x127b - 0x13a3
int64_t function_127b(void) {
    int64_t v1 = __readfsqword(40); // 0x1287
    int64_t v2; // bp-1048, 0x127b
    __asm_rep_stosq_memset((char *)&v2, 0, 127);
    bool v3; // 0x127b
    *(int32_t *)((v3 ? -1016 : 1016) + (int64_t)&v2) = 0;
    v2 = 3;
    shit(&v2, 10, 10, 0);
    for (int64_t i = 0; i < 10; i++) {
        // 0x1347
        int64_t v4; // bp-8, 0x127b
        uint32_t v5 = *(int32_t *)((int64_t)&v4 - 1040 + 4 * i); // 0x134f
        function_1090("%d\t", (int64_t)v5);
    }
    // 0x137e
    function_1070(10);
    int64_t result = 0; // 0x139a
    if (v1 != __readfsqword(40)) {
        // 0x139c
        result = function_1080();
    }
    // 0x13a1
    return result;
}

// Address range: 0x13b0 - 0x13b1
int64_t __libc_csu_init(void) {
    // 0x13b0
    int64_t result; // 0x13b0
    return result;
}

// Address range: 0x13b3 - 0x1415
int64_t function_13b3(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x13dc
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x1406
        return result;
    }
    int64_t v1 = 0; // 0x13e5
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x13f0
        v1++;
    }
    // 0x1406
    return result;
}

// Address range: 0x1420 - 0x1421
int64_t __libc_csu_fini(void) {
    // 0x1420
    int64_t result; // 0x1420
    return result;
}

// Address range: 0x1423 - 0x1425
int64_t function_1423(void) {
    // 0x1423
    int64_t result; // 0x1423
    return result;
}

// Address range: 0x1428 - 0x1429
int64_t _fini(void) {
    // 0x1428
    int64_t result; // 0x1428
    return result;
}

// Address range: 0x142b - 0x1435
int64_t function_142b(void) {
    // 0x142b
    int64_t result; // 0x142b
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// void __stack_chk_fail(void);
// int printf(const char * restrict format, ...);
// int putchar(int c);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.4.0)
// Detected functions: 27
